server:
  port : 8081
  
spring:  
  datasource:
    url: jdbc:postgresql://localhost:5432/videogamedb
    username: postgres
    password: password

video-game:
  configuration:
    pageSize: 1 
    